### ISSUE TITLE
Clean-up relative_pose_transaction_base.h

### ISSUE THREAD

**Issue by adthoms** [BEAMRobotics/beam_slam#69]
There is code in [relative_pose_transaction_base.h](https://github.com/BEAMRobotics/beam_slam/blob/c4063d2c68ae07421e0b9f90ad624c8fda210b94/bs_constraints/include/bs_constraints/relative_pose/relative_pose_transaction_base.h) that is specific to imu, and we would like to move this to a derived class.

**Comment by nickcharron** [comment]
this class has been refactored
